server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${friedChicken.datasource.driver-class-name}
    url: jdbc:mysql://${friedChicken.datasource.host}:${friedChicken.datasource.port}/${friedChicken.datasource.database}
    username: ${friedChicken.datasource.username}
    password: ${friedChicken.datasource.password}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.friedChicken.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true