server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${friedChicken.datasource.driver-class-name}
      url: jdbc:mysql://${friedChicken.datasource.host}:${friedChicken.datasource.port}/${friedChicken.datasource.database}
      username: ${friedChicken.datasource.username}
      password: ${friedChicken.datasource.password}