server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${fc.datasource.driver-class-name}
    url: jdbc:mysql://${fc.datasource.host}:${fc.datasource.port}/${fc.datasource.database}
    username: ${fc.datasource.username}
    password: ${fc.datasource.password}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.friedChicken.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
fc:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${fc.jwt.admin-secret-key}
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: ${fc.jwt.user-secret-key}
    user-ttl: 7200000
    user-token-name: authentication